#ifndef DEFINES_H_
#define DEFINES_H_

#define SENSOR_NAME_LENGTH 50
#define SENSOR_LIST_LENGTH 10
#define ACTUATORS_NAME_LENGTH 50
#define ACTUATORS_LIST_LENGTH 10
#define PIN_NAME_LENGTH 2
#define BUFFER_SIZE 255
#define UCOM_BUFFER_SIZE 255

//#define PLATFORM LPC
#define PLATFORM FREESCALE

#endif  // DEFINES_H_
