#mbed-rtos make file

OBJECTS += $(MBED_RTOS_PATH)rtx/TARGET_M0P/TOOLCHAIN_GCC/SVC_Table.o $(MBED_RTOS_PATH)rtx/TARGET_M0P/TOOLCHAIN_GCC/HAL_CM0.o $(MBED_RTOS_PATH)rtx/rt_Task.o $(MBED_RTOS_PATH)rtx/rt_System.o $(MBED_RTOS_PATH)rtx/rt_List.o $(MBED_RTOS_PATH)rtx/rt_Time.o $(MBED_RTOS_PATH)rtx/rt_Semaphore.o $(MBED_RTOS_PATH)rtx/rt_Mailbox.o $(MBED_RTOS_PATH)rtx/rt_CMSIS.o $(MBED_RTOS_PATH)rtx/HAL_CM.o $(MBED_RTOS_PATH)rtx/rt_Robin.o $(MBED_RTOS_PATH)rtx/rt_MemBox.o $(MBED_RTOS_PATH)rtx/RTX_Conf_CM.o $(MBED_RTOS_PATH)rtx/rt_Event.o $(MBED_RTOS_PATH)rtx/rt_Mutex.o $(MBED_RTOS_PATH)rtos/Thread.o $(MBED_RTOS_PATH)rtos/RtosTimer.o $(MBED_RTOS_PATH)rtos/Semaphore.o $(MBED_RTOS_PATH)rtos/Mutex.o

INCLUDE_PATHS += -I./mbed-rtos -I$(MBED_RTOS_PATH)rtx -I$(MBED_RTOS_PATH)rtx/TARGET_M0P -I$(MBED_RTOS_PATH)rtx/TARGET_M0P/TOOLCHAIN_GCC -I$(MBED_RTOS_PATH)rtos
