/*
 * NodeState.h
 *
 *  Created on: Oct 23, 2014
 *      Author: uctrl
 */

#ifndef NODE_STATE_H_
#define NODE_STATE_H_

enum InitializationState
{
	UNINITIALIZED = 0,
	LOAD_SYSTEM_CONFIG_DATA_PORT,
	LOAD_SYSTEM_CONFIG_DEVICE_MODE,
	LOAD_SYSTEM_CONFIG_G3_CONFIG,
	SHUT_DOWN_MESSAGE,
	SLEEP_SHUTDOWN,
	GET_SYSTEM_INFO_AFTER_REBOOT,
	SET_VENDOR_PRODUCT_INFO,
	SLEEP_VENDOR_PRODUCT_INFO,
	SET_TX_INFO,
	SLEEP_TX_INFO,
	SET_RX_INFO,
	SLEEP_RX_INFO,
	INITIALIZATION_FINISH,
	INITIALIZED
};

enum NetworkState
{
	DISATTACHED = 0,
	DISCOVERING,
	ATTACHED
};

enum ResponseStatus
{
	RECEIVED = 0,
	TIMEOUT	
};

#endif /* NODE_STATE_H_ */
